<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $proudct =
        [
            [
                'name' => 'Bánh Crepe Sầu riêng',
                'category_id' => '5',
                'description' => 'Bánh crepe sầu riêng nhà làm',
                'price' => '150000',
                'promotion_price' =>'12000',
                'image' => 'banh1.jpg',
                'unit' =>'hộp',
                'status' =>'1',

            ],
            [
                'name' => 'Bánh Crepe Chocolate',
                'category_id' => '6',
                'description' => 'ánh Crepe Chocolate nhà làm',
                'price' => '180000',
                'promotion_price' =>'160000',
                'image' => 'banh2.jpg',
                'unit' =>'hộp',
                'status' =>'1',

            ],
            [
                'name' => 'Bánh Crepe Sầu riêng - Chuối',
                'category_id' => '5',
                'description' => 'Bánh Crepe Sầu riêng - Chuối',
                'price' => '150000',
                'promotion_price' =>'130000',
                'image' => 'banh3.jpg',
                'unit' =>'hộp',
                'status' =>'0',

            ],
            [
                'name' => 'Bánh Crepe Đào',
                'category_id' => '5',
                'description' => 'Bánh Crepe Đào nhà làm',
                'price' => '160000',
                'promotion_price' =>'0',
                'image' => 'banh4.jpg',
                'unit' =>'hộp',
                'status' =>'0',
            ],
            [
                'name' => 'Bánh Crepe Dâu',
                'category_id' => '5',
                'description' => 'Bánh Crepe Dâu nhà làm',
                'price' => '160000',
                'promotion_price' =>'0',
                'image' => 'banh5.jpg',
                'unit' =>'hộp',
                'status' =>'1',
            ],
            [
                'name' => 'Bánh Crepe Pháp',
                'category_id' => '5',
                'description' => 'Bánh crepe sầu riêng nhà làm',
                'price' => '200000',
                'promotion_price' =>'160000',
                'image' => 'banh6.jpg',
                'unit' =>'hộp',
                'status' =>'1',
            ],
            [
                'name' => 'Bánh Crepe Táo',
                'category_id' => '5',
                'description' => 'Bánh crepe sầu riêng nhà làm',
                'price' => '180000',
                'promotion_price' =>'0',
                'image' => 'banh7.png',
                'unit' =>'hộp',
                'status' =>'0',
            ],
            [
                'name' => 'Bánh Crepe Chocolate',
                'category_id' => '5',
                'description' => 'Bánh crepe sầu riêng nhà làm',
                'price' => '180000',
                'promotion_price' =>'160000',
                'image' => 'banh8.jpg',
                'unit' =>'hộp',
                'status' =>'1',
            ],
            [
                'name' => 'Bánh Crepe Trà xanh',
                'category_id' => '5',
                'description' => 'Bánh crepe sầu riêng nhà làm',
                'price' => '160000',
                'promotion_price' =>'150000',
                'image' => 'banh9.jpg',
                'unit' =>'hộp',
                'status' =>'0',
            ],
            [
                'name' => 'Bánh Crepe Sầu riêng và Dứa',
                'category_id' => '5',
                'description' => 'Bánh crepe sầu riêng nhà làm',
                'price' => '180000',
                'promotion_price' =>'160000',
                'image' => 'banh10.jpg',
                'unit' =>'hộp',
                'status' =>'1',
            ],
            [
                'name' => 'Bánh Gato Trái cây Việt Quất',
                'category_id' => '3',
                'description' => 'Bánh crepe sầu riêng nhà làm',
                'price' => '250000',
                'promotion_price' =>'0',
                'image' => 'banh11.jpg',
                'unit' =>'hộp',
                'status' =>'0',
            ],
            [
                'name' => 'Bánh kem Chocolate Dâu',
                'category_id' => '3',
                'description' => 'Bánh crepe sầu riêng nhà làm',
                'price' => '180000',
                'promotion_price' =>'160000',
                'image' => 'banh12.jpg',
                'unit' =>'hộp',
                'status' =>'1',
            ],
            [
                'name' => 'Bánh sinh nhật rau câu trái cây',
                'category_id' => '3',
                'description' => 'Bánh crepe sầu riêng nhà làm',
                'price' => '300000',
                'promotion_price' =>'0',
                'image' => 'banh13.jpg',
                'unit' =>'hộp',
                'status' =>'0',
            ],
            [
                'name' => 'Bánh kem Dâu III',
                'category_id' => '3',
                'description' => 'Bánh crepe sầu riêng nhà làm',
                'price' => '300000',
                'promotion_price' =>'280000',
                'image' => 'banh14.jpg',
                'unit' =>'hộp',
                'status' =>'1',
            ],
            [
                'name' => 'Bánh kem Dâu I',
                'category_id' => '3',
                'description' => 'Bánh crepe sầu riêng nhà làm',
                'price' => '350000',
                'promotion_price' =>'300000',
                'image' => 'banh15.jpg',
                'unit' =>'hộp',
                'status' =>'0',
            ],
            [
                'name' => 'Bánh trái cây II',
                'category_id' => '3',
                'description' => 'Bánh crepe sầu riêng nhà làm',
                'price' => '180000',
                'promotion_price' =>'160000',
                'image' => 'banh16.jpg',
                'unit' =>'hộp',
                'status' =>'1',
            ],
            [
                'name' => 'Apple Cake',
                'category_id' => '3',
                'description' => 'Bánh crepe sầu riêng nhà làm',
                'price' => '180000',
                'promotion_price' =>'160000',
                'image' => 'banh19.jpg',
                'unit' =>'hộp',
                'status' =>'0',
            ],
            [
                'name' => 'Bánh ngọt nhân cream táo',
                'category_id' => '2',
                'description' => 'Bánh crepe sầu riêng nhà làm',
                'price' => '180000',
                'promotion_price' =>'0',
                'image' => 'banh21.jpg',
                'unit' =>'hộp',
                'status' =>'1',
            ],
            [
                'name' => 'Bánh Chocolate Trái cây',
                'category_id' => '2',
                'description' => 'Bánh crepe sầu riêng nhà làm',
                'price' => '180000',
                'promotion_price' =>'160000',
                'image' => 'banh20.jpg',
                'unit' =>'hộp',
                'status' =>'0',
            ],
            [
                'name' => 'Bánh Chocolate Trái cây II',
                'category_id' => '2',
                'description' => 'Bánh crepe sầu riêng nhà làm',
                'price' => '180000',
                'promotion_price' =>'10',
                'image' => 'Fruit-Cake_7981.jpg',
                'unit' =>'hộp',
                'status' =>'1',
            ],
            [
                'name' => 'Peach Cake',
                'category_id' => '2',
                'description' => 'Bánh crepe sầu riêng nhà làm',
                'price' => '250000',
                'promotion_price' =>'200000',
                'image' => 'Peach-Cake_3294.jpg',
                'unit' =>'hộp',
                'status' =>'0',
            ],
            [
                'name' => 'Bánh bông lan trứng muối I',
                'category_id' => '1',
                'description' => 'Bánh crepe sầu riêng nhà làm',
                'price' => '180000',
                'promotion_price' =>'160000',
                'image' => 'banhbonglantrung.jpg',
                'unit' =>'hộp',
                'status' =>'1',
            ],
            [
                'name' => 'Bánh bông lan trứng muối II',
                'category_id' => '1',
                'description' => 'Bánh crepe sầu riêng nhà làm',
                'price' => '180000',
                'promotion_price' =>'160000',
                'image' => 'banhbonglantrungmuoi.jpg',
                'unit' =>'hộp',
                'status' =>'0',
            ],
            [
                'name' => 'Bánh French',
                'category_id' => '1',
                'description' => 'Bánh crepe sầu riêng nhà làm',
                'price' => '180000',
                'promotion_price' =>'0',
                'image' => 'banh-man-thu-vi-nhat-1.jpg',
                'unit' =>'hộp',
                'status' =>'0',
            ],
            [
                'name' => 'Bánh mì Australia',
                'category_id' => '1',
                'description' => 'Bánh crepe sầu riêng nhà làm',
                'price' => '80000',
                'promotion_price' =>'0',
                'image' => 'dung-khoai-tay-lam-banh-gato-man-cuc-ngon.jpg',
                'unit' =>'hộp',
                'status' =>'1',
            ],
            [
                'name' => 'Bánh mặn thập cẩm',
                'category_id' => '5',
                'description' => 'Bánh crepe sầu riêng nhà làm',
                'price' => '150000',
                'promotion_price' =>'0',
                'image' => 'crepe-chocolate.jpg',
                'unit' =>'hộp',
                'status' =>'1',
            ]
        ];

        DB::table('products')->insert($proudct);
    }
}
